### ISSUE TITLE
Hey Sir, Like what you have done

### ISSUE THREAD

**Issue by boivinx7** [hbuckle/PSEmby#1]
I love what you have done,
But since, i have no idea what the paths.json is suppose to by I cant use the Module
I can only use the scripts in standalone.
Which is good since I can do a lot with those as exemple.
But this all seems great you should finish it up and put in on PS Gallery.

That aside could you tell me what is suppose to be in the paths.json ?

Thanks

**Comment by hbuckle** [comment]
Hi @boivinx7, glad you have found some use from this. `paths.json` has the paths to various tools and some secrets. Depending on which functions you are using you won't need all the values. This is what mine looks like

```json
{
  "alias": [
    {
      "name": "ffmpeg",
      "value": "<path to>\\ffmpeg.exe"
    },
    {
      "name": "ffprobe",
      "value": "<path to>\\ffprobe.exe"
    },
    {
      "name": "mkvmerge",
      "value": "<path to>\\mkvmerge.exe"
    },
    {
      "name": "mkvextract",
      "value": "<path to>\\mkvextract.exe"
    },
    {
      "name": "mkvpropedit",
      "value": "<path to>\\mkvpropedit.exe"
    },
    {
      "name": "eac3to",
      "value": "<path to>\\eac3to.exe"
    },
    {
      "name": "mediainfo",
      "value": "<path to>\\MediaInfo.exe"
    },
    {
      "name": "vstrip",
      "value": "<path to>\\vStrip.exe"
    },
    {
      "name": "pgcdemux",
      "value": "<path to>\\PgcDemux.exe"
    },
    {
      "name": "chaptereditor",
      "value": "<path to>\\chapterEditorCLI.exe"
    },
    {
      "name": "dgindexnv",
      "value": "<path to>\\DGIndexNV.exe"
    },
    {
      "name": "bdsup2sub",
      "value": "<path to>\\bdsup2sub++.exe"
    }
  ],
  "script": [
    {
      "name": "vspipe",
      "value": "<path to>\\VSPipe.exe"
    },
    {
      "name": "x264",
      "value": "<path to>\\x264.exe"
    },
    {
      "name": "tmdb_api_key",
      "value": "xxx"
    },
    {
      "name": "bing_api_key",
      "value": "xxx"
    },
    {
      "name": "emby_api_key",
      "value": "xxx"
    }
  ]
}
```

I should point out that I wrote this module to deal with my own Emby setup, which is quite customised, so please be careful, I wouldn't want it to mess up any of your metadata by accident.
Let me know if you need anything else.

**Comment by boivinx7** [comment]
Thanks, Yes no problem for my metadata, I just migrated to a new server, so the old one is all fine.
My problem is migrating ;)
Thanks for the quick response.
